# Generated by Django 5.0.1 on 2024-01-09 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_comment_bid_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 22, 5, 1, 22999, tzinfo=datetime.timezone.utc)),
        ),
    ]
