# Generated by Django 5.0.1 on 2024-01-09 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 22, 5, 23, 199320, tzinfo=datetime.timezone.utc)),
        ),
    ]
