# Generated by Django 5.0.1 on 2024-01-11 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 11, 4, 20, 16, 959197, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='static\\auctions\\images'),
        ),
    ]
